### ISSUE TITLE
有特殊符号的正文内容不能被正确stringnify传

### ISSUE THREAD

**Issue by zhongyizh** [zhongyizh/hipond-serverless#10]
Post内容如果有特殊符号，例如？《》，点击进入详情页会报错。
原因是通过stringnify Json object的时候特殊符号会影响最后输出的string，导致string没法被正确解析

**Comment by IsaacYingqiMa** [comment]
在index.js中navigate到detail页面的url中对post内容使用URLencoder使特殊符号不会被识别为URL的操作字符
