### ISSUE TITLE
编辑post不改变图片，会将post的审核状态设为false

### ISSUE THREAD

**Issue by zhongyizh** [zhongyizh/hipond-serverless#28]
1. 点进自己的贴子，点编辑
2. 拖拽调换图片的顺序（或者只修改文字内容，或者什么都不改）
3. 此时帖子里的图片跟之前是一样的，不需要去增加或删除，也不需要去重新审核，但是贴子的isImgChecked属性会被设为false
4. 后端的审核方法不会被触发，因此贴子的isImgChecked会一直是false

**Comment by IsaacYingqiMa** [comment]
已解决
